version: "3"

services:
  configuracion:
    image: saulfeliciano/confserver
    networks:
      - final
    volumes:
      - /home/saulfeliciano/configsFinal:/var/centralConf
    ports:
      - 8888:8888
    restart: on-failure
    logging:
      driver: none

  descubrimiento:
    image: saulfeliciano/eurekaserver
    networks:
      - final
    depends_on:
      - configuracion
    ports:
      - 8761:8761
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
    restart: on-failure
    logging:
      driver: none

  perimetral:
    image: saulfeliciano/balanceador
    networks:
      - final
    depends_on:
      - configuracion
      - descubrimiento
    ports:
      - 8080:8080
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
    restart: on-failure
    logging:
      driver: none

  usuariomicro1:
    image: saulfeliciano/eventmicroservice
    networks:
      - final
    depends_on:
      - dbusuario
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  usuariomicro2:
    image: saulfeliciano/eventmicroservice
    networks:
      - final
    depends_on:
      - dbusuario
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  usuariomicro3:
    image: saulfeliciano/eventmicroservice
    networks:
      - final
    depends_on:
      - dbusuario
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  eventomicro1:
    image: saulfeliciano/eventmicroservice2
    networks:
      - final
    depends_on:
      - dbevento
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  eventomicro2:
    image: saulfeliciano/eventmicroservice2
    networks:
      - final
    depends_on:
      - dbevento
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  eventomicro3:
    image: saulfeliciano/eventmicroservice2
    networks:
      - final
    depends_on:
      - dbevento
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  mensajeriamicro1:
    image: saulfeliciano/notificationsservice
    networks:
      - final
    depends_on:
      - dbmensajeria
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  mensajeriamicro2:
    image: saulfeliciano/notificationsservice
    networks:
      - final
    depends_on:
      - dbmensajeria
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  mensajeriamicro3:
    image: saulfeliciano/notificationsservice
    networks:
      - final
    depends_on:
      - dbmensajeria
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  dbusuario:
    image: mysql:5.7.26
    networks:
      - final
    ports:
      - "1234:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=userservice
    volumes:   #volumen de datos utilizado.
      - ~/dato_mysql_final:/var/lib/mysql

  dbevento:
    image: mysql:5.7.26
    networks:
      - final
    ports:
      - "1235:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eventservice
    volumes:   #volumen de datos utilizado.
      - ~/dato_mysql_final:/var/lib/mysql

  dbmensajeria:
    image: mysql:5.7.26
    networks:
      - final
    ports:
      - "1236:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notificationsservices
    volumes:   #volumen de datos utilizado.
      - ~/dato_mysql_final:/var/lib/mysql
networks:
  final: